### ISSUE TITLE
When will musicbrainz IDs be supported?

### ISSUE THREAD

**Issue by PradatiusD** [raoulmillais/node-7digital-api#70]
I was made aware yesterday that the 7Digital API **will now be supporting Musicbrainz IDs**.  This will allow us to be able to access artists with `sevenDigitalids=` OR `musicBrainzIds=`

Example calls are laid out below:

> With 7Digital ID
> http://api.7digital.com/1.2/artist/match/byId?country=us&oauth_consumer_key=YOUR_KEY_HERE&oauth_nonce=989288088&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1426096192&oauth_version=1.0&sevenDigitalIds=10869&oauth_signature=%2F2r4dlCR9RF4JYIhRg78%2BMcd3cQ%3D

> With Musicbrainz ID
> http://api.7digital.com/1.2/artist/match/byId?country=us&musicBrainzIds=25607613-aceb-445a-8519-83a2ee0f8402&oauth_consumer_key=YOUR_KEY_HERE&oauth_nonce=346135565&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1426096485&oauth_version=1.0&oauth_signature=V7HFzaKSvt0HZLpBzcGvCvUgg%2BA%3D

I understand that it will take time to develop and implement this new schema to this Node.js client (and I bet that 7Digital is still iterating on its first release of this data).  My question is, **when do you all plan on supporting this**?

Thanks so much!
Daniel

**Comment by raoulmillais** [comment]
Implementing support for this will actually be quick and easy.  I think it makes more sense to wait until we've released support for matching release and tracks as well though.  If you're still keen just to get going with artist matching then I could get something for you to test with in the next few days.

**Comment by PradatiusD** [comment]
No need to rush that.  We'll await when the release and track matching is good to go.  When do you think that will be ready?

**Comment by raoulmillais** [comment]
We are working on it at the moment.

**Comment by PradatiusD** [comment]
Any updates? 

Thank you so much!

**Comment by raoulmillais** [comment]
We are very close. I *think* most of the work has been completed noow and the team is reviewing and documenting, but I can't promise exactly when it will be live for customers.

**Comment by AnthonySteele** [comment]
Give it a try, we now have 3 endpoints for matching now: `/artist/match/byId`,  `/release/match/byid` and `track/match/byid`. 

It may not be final yet, but it's at a stage where feedback would be appreciated.

All three queries work the same - supply either the `sevenDigialIds` or `musicBrainzIds` params, with value containing 1 or more ids separated by comas.

**Comment by PradatiusD** [comment]
@AnthonySteele are you referring to the main 7Digital API or this Node.js SDK?  

I am aware that 7Digital is almost completed with their matching API.  I am just awaiting for when this Node.js client will be ready to do it.

Thanks again!

**Comment by raoulmillais** [comment]
Hi, @AnthonySteele is referring to it being ready in the API. I'm hoping to add it to this client in the next day or two.  The build is broken on master, which needs to be resolved first.

**Comment by raoulmillais** [comment]
I have just pushed and published experimental matching API support as 0.33.0  Please have a test and give us any feedback.

**Comment by raoulmillais** [comment]
Apologies, I specified the wrong oauth type.  This is now tested and fixed in 0.33.1, please use that version for testing.

**Comment by PradatiusD** [comment]
Thank you @raoulmillais and the rest of the team!  The matching is working great.  I'm using it mostly right now at the artist level, and I'll be sure to let you know if I see anything.

Quick question:  How do I remove the logging output?  Is there a setting when I instantiate the API class that controls that?

**Comment by raoulmillais** [comment]
Yes you can configure a custom logger using any of the usual configuration points.  You can supply a logger object, which should have a function for each of the npm loglevels.  The default logger can be found in [here](https://github.com/raoulmillais/node-7digital-api/blob/08e2098d263ffaf7cdc8af4036a1dc8880366a5e/lib/logger.js#L25).  So for example:

```javascript
function noop() {}
var quietLogger = { 
    silly: noop, 
    verbose: noop, 
    info: noop, 
    http: noop, 
    warn: noop, 
    error: console.error 
};
var api = require('7digital').configure({ 
    logger: quietLogger 
    // remaining config here
} });
api.Releases().matchById({ sevendigitalIds: '12345' }, console.log);
```

**Comment by raoulmillais** [comment]
@PradatiusD please send any ffeedback you have about the matching API specifically to your account manager.  That way it will definitely get to the right people :)  As always, feedback or issues with the node client can be done here.

**Comment by raoulmillais** [comment]
Morning @PradatiusD - A quick heads up that a new version of the matching API was deployed this morning.  For consistency, the `musicBrainzIds` parameter has now changed to `mbids` and in the response, the `musicBrainzId` property has changed to `mbId`. cc @AnthonySteele

**Comment by PradatiusD** [comment]
Excellent. Thanks for letting me know.  I will adjust accordingly.
